version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3030:3030
        volumes:
            - .:/app
            - /usr/src/app/node_modules
